# #####################################################################
# ツール名:GitLab
# coding:utf-8
# Copyright (c) Flugel System Studio Inc. - All rights reserved.
# #####################################################################

version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab
    container_name: gitlab
    volumes:
      - ./gitlab/etc:/etc/gitlab
      - ./gitlab/log:/var/log/gitlab
      - ./gitlab/opt:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.3.3'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
    ports:
      - "80:80"
      - "8022:22"
    networks:
      gitlab_net:
        ipv4_address: 172.16.238.2
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    hostname: gitlab-runner
    container_name: gitlab-runner
    volumes:
      - ./runner/gitlab-config:/etc/gitlab-runner
      - ./runner/var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
    networks:
      gitlab_net:
        ipv4_address: 172.16.238.3

networks:
  gitlab_net:
    ipam:
      config:
        - subnet: 172.16.238.0/24
